mountetna/magma

- db/migrations/038_add_reference_patient.rb
- gem/lib/magma/attribute.rb
- gem/lib/magma/attributes/link.rb
- gem/lib/magma/model.rb
- gem/lib/models/patient.rb
This adds link_model to attributes, which allows you to set a model name other than the column name for a given attribute (e.g. the attribute 'physician' can have model 'doctor' instead of defaulting to model 'physician')
> support link_model on link attributes

- lib/magma/attributes/table.rb
- lib/magma/model.rb
- lib/magma/payload.rb
- lib/magma/server/retrieve.rb
This is a small improvement to the retrieve endpoint which makes it not use eager loading for tables if the 'collapse_tables' option is specified (and makes that option mandatory for tsv format), useful for just grabbing one table. The other mode is used in the 'browse' window to grab an associated table (e.g. i am on a rna_seq page and want to list gene_exp for that record)
> don't eager load tables if collapse_tables is true

- lib/magma/storage.rb
Following the use of the Question interface to get records, we now use fog's get_url method to generate an s3 url (instead of letting carrierwave do it through the Sequel model) - however, carrierwave seems to put files into an 'uploads/' directory in s3. We need to format our path correspondingly.
> add uploads/ to s3 storage path

- lib/magma/payload.rb
- spec/update_spec.rb
This is the price I pay for weak test assertions - my update endpoint correctly changed the DB but returned a 500 instead of a 200 due to some stupid error. I added better assertions and fixed the error.
> fix sometime lack of attribute_names

- lib/magma/attributes/collection.rb
- lib/magma/query/constraint.rb
- lib/magma/query/join.rb
- lib/magma/query/predicate.rb
- lib/magma/query/predicate/boolean.rb
- lib/magma/query/predicate/column.rb
- lib/magma/query/predicate/date_time.rb
- lib/magma/query/predicate/file.rb
- lib/magma/query/predicate/metrics.rb
- lib/magma/query/predicate/model.rb
- lib/magma/query/predicate/number.rb
- lib/magma/query/predicate/record.rb
- lib/magma/query/predicate/string.rb
- lib/magma/query/predicate/terminal.rb
- lib/magma/query/predicate/vector.rb
- lib/magma/query/question.rb
- lib/magma/query/verb.rb
- lib/magma/server/query.rb
- spec/query_spec.rb
- spec/retrieve_spec.rb
This cleans up the "predicate" classes that are used by the Query interface, to clarify the way they work. Mostly this consists of getting rid of switch statements and adding a "verb" interface that matches argument sequences in the query. The result is much cleaner classes that are easier to extend.
I have also added a few new verbs - ::any and ::count to the ModelPredicate and a bunch of new comparison/equality tests to the various value predicates.
There is also a reporting interface on the query endpoint (query('::predicates')) which returns the available predicates and the verb arguments they accept.
> Graft improve predicate interface

- lib/magma.rb
- lib/magma/attributes/image.rb
- lib/magma/commands.rb
- lib/magma/payload.rb
- lib/magma/revision.rb
- lib/magma/server.rb
- lib/magma/server/update.rb
- spec/update_spec.rb
This fixes a few update-related bugs:
1) Thumbnail display was broken because the URL was not generated correctly, and S3 does some weird things with filenames.
2) The main update loop would not return a correct payload, resulting in empty values being returned, which would wipe out part of the record in the JS store (which could lead to bad revisions in the future) - e.g., if I edit a patient, the returned JSON document describing the update might have NULL for the 'sample' collection attribute instead of [ 's1', 's2' ] - if you then re-edited the patient, you began with a NULL entry, very bad. All of this began because the Magma::Payload class was reformed for the retrieve endpoint, but also got used by the update endpoint to send back revisions; this was not working.
The …
> Graft fix update revision payload

- lib/magma.rb
- lib/magma/commands.rb
- lib/magma/project.rb
- lib/magma/server/retrieve.rb
- spec/labors/models/monster.rb
- spec/magma_model_spec.rb
- spec/magma_spec.rb
This does two main things:
1) Adds Magma#get_project, Magma#magma_projects, which make use of a new Magma::Project class which collects all of its own models and so on.
2) Adds in a bunch of validations when the model loads:
- There must be a Project model for each project
- Model names cannot be certain reserved words
- Models must have reciprocal links - if A links to B, B must link to A somehow.
- Models cannot be orphans - they must link to another model
There is a problem with the orphan model test, which is that you can have two or more orphans clutching each other and still disconnected from the Project model, really we should validate that there is a path to Project somehow.
> Graft fix linking and validation

- lib/magma/query/query_executor.rb
- lib/magma/query/question.rb
- lib/magma/server/query.rb
- spec/query_executor_spec.rb
- spec/query_spec.rb
- spec/spec_helper.rb
related to this issue #65 
- Manage the query timeouts within the question, so that database roles don't have to be changed and timeouts can be managed for read queries
- query is done inside a transaction with a local statement_timeout, only works for postgres
- timeout set to 5 minutes in the query controller
> query time out

- lib/magma/server/retrieve.rb
- spec/query_spec.rb
- spec/retrieve_spec.rb
- spec/spec_helper.rb
- spec/update_spec.rb
A victim of poor test coverage, a previous change, meant to prevent 'grabbing the entire dataset' also prevented 'grabbing just the identifiers for the entire dataset'. I fixed, added in a test to cover the specific case, and made some stylish improvements to the spec.
> fix retrieve endpoint to re-allow grabbing identifiers (only) for all records/models

- lib/magma/server.rb
The Sequel query-logging seems to have been axed in the etna-server update, adding it back in.
> support logging in db again

- lib/magma.rb
This is a simple modification that allows the root project model to run on it's own. This helps during initial project setup.
> Allows the root project model to run by itself.

- config.ru
This lets magma use the new etna cross_origin rack layer, which allows it to respond correctly to CORS requests from browsers (so, e.g., timur.ucsf.edu can talk directly to magma.ucsf.edu via the browser).
> adds etna::cross_origin layer so magma can serve requests to browser clients

- Gemfile
- Gemfile.lock
Since projects have loader code, they will inevitably accumulate external dependencies. Rather than adding them to the base magma Gemfile, this simply loads a Gemfile from each projects/whatever/ directory, so each project can define its own dependencies. Note this assumes that the project_path is projects/*, which may not be true depending on the individual config.yml.
> allow each project repo to track its own gems and bundle with magma's Gemfile

- gem/lib/client.rb
- gem/magma.gemspec
- spec/client_spec.rb
- spec/spec_helper.rb
This enables status_check in the magma client and also changes the way the client spec works so that it uses webmock instead of stubbing out internal client methods. Now the client stack is tested completely (except this depends on fixing a problem with Etna::TestAuth, so the spec won't pass until that is updated).
> fix client status_check

- lib/magma/server/retrieve.rb
- spec/retrieve_spec.rb
At some point (due to a rather poorly-written interface in the function RetrieveController::retrieve_model) a regression was introduced when using the option collapse_tables (which removes table attributes from the results, used, e.g., by the Search page) that caused all pages to return instead of a specific page. This PR fixes that issue and adds a test to cover this case.
> fix pagination issue in retrieve

- lib/magma/project.rb
This is a fix to adjust the way tables are output when planning a migration.
The existing plan command outputs tables in some unspecified order - this can result in an initial migration which does not work, because a create_table may contain foreign keys to tables that do not exist yet.
This PR attempts to fix that by outputting tables in a breadth-first order based on parent models, to attempt to ensure that there are no foreign key conflicts. This doesn't prevent all situations from causing trouble (e.g. circular links between models), but it should do most of the time.
> adjust model ordering in project migration

- lib/magma/commands.rb
This adds a 'create_db' command, which is a utility to attach a project to a magma instance.
There are several elements to setting up a complete project:
1) Correct database configuration
2) Project models and migrations
3) Data
This command provides (1). Given a config.yml containing a database name, user, and password which specify a valid postgres role, the create_db <project_name> command will ensure that the database exists and the schema for the specified project exists. Subsequently you can create or run migrations using an existing set of models.
If you previously created a database through postgres, you might have to change the owner of that database to the role in your config.yml in order to use this command, otherwise schema creation will not work.
> create_db command

- lib/magma/retrieval.rb
- lib/magma/server/retrieve.rb
- spec/retrieve_spec.rb
- spec/spec_helper.rb
Fixes another bug due to my poorly-written retrieval code with hard-to-follow logic. Somehow it was previously excluding all table attributes from display, rather than only excluding them if the 'collapse_tables' param to /retrieve is true. Fixed, along with tests to ensure this stays in place.
> fix table retrieval problem

- Gemfile
- Gemfile.lock
- lib/magma.rb
- lib/magma/file_uploader.rb
- lib/magma/image_uploader.rb
- lib/magma/query/constraint.rb
- lib/magma/query/join.rb
- lib/magma/query/predicate.rb
- lib/magma/query/predicate/record.rb
- lib/magma/query/predicate/vector.rb
- lib/magma/query/question.rb
- lib/magma/server/query.rb
- spec/query_spec.rb
This PR solves a bug in the /query API that removed some items from the response incorrectly, due to outer-joining tables on foreign key criterion (correctly producing rows with NULL values) but then applying filters to these rows in WHERE clauses (incorrectly remove rows with some NULL values). See discussion of the problem in #100 - the resolution was to move filtering criterion into the JOIN ON clause for mapped columns, but to keep those criterion in WHERE clauses for filters on the table.
The final result was incompatible with the current plot code, so this has been waiting on the completion of the timur branch `em-d3-v5`.
> Graft fix query

- lib/magma/attributes/collection.rb
- spec/update_spec.rb
Apparently since April 2016 we have not been setting created_at or updated_at when we create new models; this data is thus all missing or out-of-date. This PR patches this error at least at the update endpoint level, although perhaps some NOT NULL constraints are in order to prevent this sort of thing more definitively.
> insert created_at and updated_at via update endpoint for new models

- lib/magma/query/predicate/matrix.rb
Just a small bugfix, the select for a matrix attribute should never retrieve values in the main query SQL, as this selection happens in a separate query to allow caching.
> don't select matrix column in query

- lib/magma/attribute.rb
- lib/magma/attributes/boolean_attribute.rb
- lib/magma/attributes/child.rb
- lib/magma/attributes/collection.rb
- lib/magma/attributes/date_time_attribute.rb
- lib/magma/attributes/file.rb
- lib/magma/attributes/float_attribute.rb
- lib/magma/attributes/integer_attribute.rb
- lib/magma/attributes/json_attribute.rb
- lib/magma/attributes/match.rb
- lib/magma/attributes/matrix.rb
- lib/magma/attributes/string_attribute.rb
- lib/magma/attributes/table.rb
- lib/magma/model.rb
- spec/labors/models/aspect.rb
- spec/labors/models/codex.rb
- spec/labors/models/labor.rb
- spec/labors/models/monster.rb
- spec/labors/models/prize.rb
- spec/labors/models/victim.rb
- spec/migration_spec.rb
- spec/retrieve_spec.rb
#113 
This will start work on the linked ticket. It will make the `#attribute` method private within the `model` class and allow for attribute creation by using `data_type :attribute_name` where the allowed data_types are `string`, `integer`, `boolean`, and `date_time`.
> Change attribute definitions

- lib/magma/attribute.rb
- lib/magma/migration.rb
- lib/magma/query/predicate/record.rb
- lib/magma/retrieval.rb
#113 
Refactor `#attribute_child` method to use new attribute classes.
> Refactor attribute_child method to not use types

- lib/magma/query/predicate.rb
- lib/magma/query/predicate/matrix.rb
- lib/magma/query/question.rb
- lib/magma/query/verb.rb
- lib/magma/server/query.rb
- spec/query_spec.rb
While poking around in Magma::MatrixAttribute to try and figure out #119, I discovered that the '::slice' verb to the Magma::MatrixPredicate behaves poorly (i.e., 500s) with invalid arguments. Normally the argument to slice should be an array of strings mapping to the column names associated with the matrix attribute (e.g. `[ ..., 'matrix', '::slice', [ 'GENE1', 'GENE2' ] ]`). The list of valid column names is currently shoved into the match parameter of the matrix attribute; if the arguments to the column name are invalid, Magma errors when trying to extract the slice. Instead, it should return a 422 to the user with some instructions on what to fix.
To support this, this PR does two things:
1) A validation interface is added to `Magma::Verb`. This allows the verb to examine the …
> Graft fix matrix slice

- projects/example/models/example_patient.rb
- projects/example/models/example_project.rb
Per https://github.com/mountetna/magma/pull/118, attribute is no longer available in `Magma::Model`s.
> Remove attribute usage in example proejct models

- README.md
- db/migrations/001_add_attributes.rb
- lib/magma/attribute.rb
- lib/magma/commands.rb
- projects/example/models/example_patient.rb
- projects/example/models/example_project.rb
- spec/labors/models/project.rb
- spec/magma_attribute_spec.rb
- spec/magma_model_spec.rb
Per #99, this PR adds a global `attributes` table that stores attribute options `desc`, `display_name`, `match`, and `format_hint`. Options will be fetched from the `attributes` table for a project/model/attribute if it exists; otherwise, we'll continue to use the definition in the model file.
This PR also adds a `global_migrate` command to run database wide migrations. It could be merged into `migrate`, but handling the version flag could be weird. How would we tell if the requested version is for a global migration or a project specific migration?
This is our first pass through this problem -- we're happy for all feedback! 😄
/cc @notmarkmiranda
> Make chosen attribute options editable

- lib/magma/attribute.rb
- lib/magma/attributes/boolean_attribute.rb
- lib/magma/attributes/date_time_attribute.rb
- lib/magma/attributes/file.rb
- lib/magma/attributes/float_attribute.rb
- lib/magma/attributes/integer_attribute.rb
- lib/magma/attributes/match.rb
- lib/magma/attributes/matrix.rb
- lib/magma/attributes/string_attribute.rb
- lib/magma/migration.rb
- lib/magma/model.rb
- spec/labors/models/labor.rb
- spec/labors/models/monster.rb
- spec/labors/models/project.rb
- spec/labors/models/victim.rb
- spec/migration_spec.rb
`Magma::Model#identifier` sets the type to string so there's no need to set it in the definitions.
https://github.com/mountetna/magma/blob/d6764d31e6e64b9447f6480e6af58cf14c3db0e1/lib/magma/model.rb#L50-L57
Also, update `Magma::Model#identifier` so `opts` defaults to an empty hash. Some spec models don't set any options.
> Remove identifier type from spec models

- lib/magma/attribute.rb
- lib/magma/attributes/identifier_attribute.rb
- lib/magma/attributes/link_attribute.rb
- lib/magma/attributes/parent_attribute.rb
- lib/magma/model.rb
- lib/magma/project.rb
- lib/magma/retrieval.rb
- spec/query_spec.rb
- spec/retrieve_spec.rb
#125 
This will refactor identifier, parent, and link to match the other attribute patterns. The only holdover was that the previous #parent method was a getter and setter method. There is an instance variable set in the define method group in order to set the parent on the model.
> Refactor identifier, parent, and link attributes

- lib/magma/attribute.rb
- spec/magma_attribute_spec.rb
Since we've added new attribute classes, such as `Magma::BooleanAttribute` and `Magma::LinkAttribute`, `Magma::Attribute#json_template` has new values for `attribute_class`. This breaks the API for consumers like timur.
To keep the API consistent, we'll continue using the old attribute class names in `#json_template`. 
This should get timur back to a working state without needing any changes. Since I'm newer to timur, I could use another set of eyes to verify things work 😄
> Use old attr class names in json_template

- db/migrations/002_add_validation_to_attributes.rb
- lib/magma/attribute.rb
- lib/magma/validation_object.rb
- spec/magma_attribute_spec.rb
- spec/validation_spec.rb
This PR follows up on https://github.com/mountetna/magma/pull/135 by adding attribute validation options to the attributes table. Like the other `Magma::Attribute::EDITABLE_OPTIONS`, validation options stored in the attributes table will be loaded in favor of any defined on models in Ruby.
There is a little weirdness around updating validation options that are already loaded in memory. When we convert validations to validation objects, we cache the validation object.
https://github.com/mountetna/magma/blob/453cf160ffc7207a4ac7e25d2bb027ebc683e179/lib/magma/attribute.rb#L29-L31
So if a validation that was already loaded in memory is changed in the attributes table, the validation object will still be based on the old validation data.
```ruby
irb(main):002:0> …
```
> Add attr validation options to attributes table

- lib/magma/project.rb
I must have not saved before committing / pushing on #144.
This will fix the trailing .map on #ordered_models.
> Hotfix for link_model in project.rb

- spec/update_spec.rb
This will temporarily skip the update file spec until we have a chance to fix it.
> Skip update file spec

- lib/magma/attribute.rb
- lib/magma/validation_object.rb
- spec/magma_attribute_spec.rb
#128 
This removes model_name from json_template and adds the validation_object
directly to json_template.
> Clean up json_template

- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- README.md
- config.yml.test
- spec/retrieve_spec.rb
This PR sets up a GitHub Actions workflow that will run the test suite on every push and PR.
Here are a couple of example runs:
* https://github.com/mountetna/magma/actions/runs/116143494
* https://github.com/mountetna/magma/actions/runs/116903644
If you click on the "build" link on the left sidebar, you can see all the steps that happened for each run.
GitHub Actions also gives us a status badge that I've included in the [README](https://github.com/mountetna/magma/blob/c8bc242ad88e6892397aa175eaa782893398bef8/README.md).
There are a few changes we had to make so GitHub Actions could run the test suite.
* Relax the Ruby version in the Gemfile because GitHub Actions only supports major.minor Ruby versioning. https://github.com/mountetna/magma/commit/100aa63cef4971741d6a4b2772ba6a0cd6b2b8fd …
> Use GitHub Actions to run test suite

- lib/magma/server.rb
- spec/server_spec.rb
Trying to view magma in the browser should give you a basic status message. Instead, you get a 503 because the rack format for the route '/' is broken! This PR repairs this issue.
> Fix root route

- lib/magma/retrieval.rb
- spec/retrieve_spec.rb
This fixes a flaky failure that happened after https://github.com/mountetna/magma/pull/151.
https://github.com/mountetna/magma/runs/721348936
I'm assuming the TSV header order doesn't matter, so I used the `match_array` helper to verify the header elements are present without worrying about the order. If the order matters, we can try something else.
> Update retrieve TSV spec

- lib/magma.rb
- lib/magma/attribute.rb
- lib/magma/attributes/child.rb
- lib/magma/attributes/collection.rb
- lib/magma/attributes/link.rb
- lib/magma/attributes/table.rb
- spec/magma_spec.rb
To help make `Magma#validate_models` a little more digestible, I also moved Magma attribute validations into `#validate_attributes`.
Fixes #130
> Validate attributes exist in model tables

- lib/magma/actions/action_error.rb
- lib/magma/actions/update_attribute.rb
- lib/magma/server.rb
- lib/magma/server/update_model.rb
- spec/server/update_model_spec.rb
- spec/spec_helper.rb
This PR adds a /update_model API endpoint per #131. So far it supports updating an attribute's options.
The endpoint is backed by the newly added `UpdateModelController`. It will iterate over the array of actions it receives, and defer to action classes to perform those actions. For example, an `update_attribute` action will be performed by `Magma::UpdateAttribute`.
In addition to performing actions, each action class is responsible for validating its action params. This division of responsibilities will help keep `UpdateModelController` pretty stable as we add new actions. It will also make it easier for us to parallelize the work going forward.
We've also restricted the endpoint to superusers based on conversations we've had in the past. We can change the permissions if something else …
> Add /update_model API endpoint

- spec/fixtures/movies/models/villain.rb
- spec/magma_project_spec.rb
- spec/server/update_model_spec.rb
https://github.com/mountetna/magma/commit/f56a5c0406b7ba7ebaf178307d6403abcd11bd07 resets attributes that get changed in tests. `Magma::Attribute#update_option` changes options in memory that persist between test runs. As a result, attribute changes in `UpdateModelController` spec can cause other tests to fail. For example, prior to this commit `rspec spec/server/update_model_spec.rb spec/magma_commands_spec.rb --seed 18642` would fail. Before we tackle the bigger challenges around global state, we can manually reset attributes that get changed.
https://github.com/mountetna/magma/commit/5fcbebab11292527cc723ef7424b9164898f3857 adds a new fixtures project called Movies that can be used to verify the behavior of projects with Ruby backed model definitions. This helps give us more confidence …
> Test fixes

- lib/magma/commands.rb
- lib/magma/dictionary.rb
- spec/fixtures/template.json
- spec/magma_commands_spec.rb
- spec/retrieve_spec.rb
There's a little weirdness around loading model dictionaries from the template file because the model dictionary JSON is represented differently in the models table and the models JSON template.
In the models table, it looks like
https://github.com/mountetna/magma/blob/ef767145c933f0186474a3efce27b7170693be8e/spec/fixtures/labors_model_attributes.yml#L2
and in the template file it looks like
https://github.com/mountetna/magma/blob/0f5b7daf56417fc35fd0b60dbdd670b524d0c831/spec/fixtures/template.json#L188-L198
I added `dictionary_model` to the template so we can properly insert model dictionaries in `load_project`. So we can work around the dictionary JSON formats being different, but it might be worth consolidating it so it's consistent.
This PR also does a little bit of clean up on the …
> Load project models in the load_project command

- lib/magma/actions/model_update_actions.rb
- lib/magma/actions/update_attribute.rb
- lib/magma/attribute.rb
- lib/magma/server/update_model.rb
- spec/actions/model_update_actions_spec.rb
- spec/actions/model_updater_spec.rb
- spec/actions/update_attribute_actions_spec.rb
- spec/fixtures/movies/models/villain.rb
- spec/magma_project_spec.rb
- spec/server/update_model_spec.rb
#164 
The `UpdateModelController` was overloaded with logic that made it difficult to test. The only way to properly test the controller was correctly parsing incoming parameters was with a request spec.
This change will allow unit and function tests to be written against the actions that are created. Errors bubble up from the base level, through the `ModelUpdateAction` and into the controller.
> Extract logic from update_model_controller

- lib/magma.rb
- lib/magma/actions/update_attribute.rb
- lib/magma/attribute.rb
- lib/magma/attributes/child.rb
- lib/magma/attributes/collection.rb
- lib/magma/attributes/file.rb
- lib/magma/attributes/foreign_key.rb
- lib/magma/attributes/identifier_attribute.rb
- lib/magma/attributes/image.rb
- lib/magma/attributes/link.rb
- lib/magma/attributes/link_attribute.rb
- lib/magma/attributes/matrix.rb
- lib/magma/attributes/parent_attribute.rb
- lib/magma/attributes/table.rb
- lib/magma/model.rb
- lib/magma/project.rb
- lib/magma/revision.rb
- spec/actions/update_attribute_actions_spec.rb
- spec/magma_attribute_spec.rb
- spec/magma_child_attribute_spec.rb
- spec/magma_spec.rb
- spec/server/update_model_spec.rb
- spec/spec_helper.rb
- spec/validation_spec.rb
By making `Magma::Attribute` inherit from `Sequel::Model`, we can leverage Sequel's API to manage data we get from the attributes table. This will help us avoid issues like https://github.com/mountetna/magma/pull/173#issuecomment-644144794 that come up from us trying to manage everything ourselves.
To get this to work, we have to make a number of changes. A few that stand out
* Configure Sequel after connecting to the database so Sequel is available in both `Magma::Attribute` and `Magma::Model`
* Use Sequel's [single table inheritance](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/SingleTableInheritance.html) plugin to support `Magma::Attribute` subclasses (`Mamga::StringAttribute`, `Magma::IntegerAttribute`, etc.)
* Rename `Magma::Attribute#model` to `#magma_model` …
> Make Magma::Attribute inherit from Sequel::Model

- lib/magma/attribute.rb
The Sequel single table inheritance plugin allows for the model_map to be defined using a Proc. The Proc will receive the `type` column value and convert it to a `Magma::Attribute `class (e.g. `Magma::StringAttribute`).
Fixes #183
> Use a Proc for Magma::Attribute single table inheritance model map

- lib/magma/actions/add_attribute.rb
- lib/magma/actions/add_model.rb
- lib/magma/actions/base_action.rb
- lib/magma/actions/model_update_actions.rb
- lib/magma/actions/update_attribute.rb
- lib/magma/project.rb
- spec/actions/add_attribute_actions_spec.rb
- spec/actions/add_model_action_spec.rb
- spec/actions/model_update_actions_spec.rb
- spec/actions/update_attribute_actions_spec.rb
- spec/server/update_model_spec.rb
- spec/spec_helper.rb
This PR builds on top of https://github.com/mountetna/magma/pull/181.
`Magma::AddModelAction` will add the new model and define link relationships. It makes changes to both the database and in memory so we can build and run migrations for the new model in `Magma::ModelUpdateAction`.
This PR also makes a change to `Magma::BaseAction#validate`. Before, it would stop doing validations if any action validation failed. While this might save some code cycles, it could lead to a poor user experience because users would have to make multiple requests to find all validation issues. Now `Magma::BaseAction#validate` will let all validations run so we can collect all validation problems in one request cycle. Along the same lines, `Magma::UpdateAttributeAction#validate` has been updated to do more …
> Support add_model in /update_model API

- Gemfile.lock
- lib/magma/attributes/collection.rb
- spec/retrieve_spec.rb
This PR separates the Collection `payload` format from its `tsv` format. Previously the `tsv` format called `query_to_payload` internally, which caused the collection value to attempt to reformat / flatten twice, resulting in exceptions (and would result in users not being able to download TSV files in Timur, if they involved a collection attribute). This change removes the second formatting attempt and also adds a test to check behaviour.
> Add test for TSV + collection; update collection query_to_tsv

- lib/magma/attributes/table.rb
- lib/magma/loader.rb
- lib/magma/loader/record_entry.rb
- lib/magma/loader/tsv.rb
- lib/magma/revision.rb
- lib/magma/server/update.rb
- spec/labors/migrations/12_remove_unique_on_prize.rb
- spec/update_spec.rb
This adds some basic support in the /update endpoint for updating `table` attributes. There were two main issues to resolve:
1) It is customary to use `table` to link to a leaf model with no identifier (that is, just an ancillary table attached to this model; the only relevant identifier is the parent's), in which case many Magma operations substitute the database `id` column for the identifier. The /update revision format, however, posts changes as { identifier => { identifier_changes } }. If we are inserting new records, there must be a way for us to specify a non-existent id (that is, cause the insertion to create a new id).
2) There might be existing records in a table that should be removed before inserting new values.
Here I have implemented (1) and not (2). I think it is possible …
> Support table attribute in /update

- lib/magma/attribute.rb
Without a `key_map`, the Sequel single table inheritance plugin will use the `model_map` to insert values into the database. For `Magma::Attribute`, this resulted in types being inserted as Ruby classes (i.e., `Magma::IntegerAttribute`) instead of strings (i.e., `integer`). By configuring `key_map`, we can make sure `Magma::Attribute` types are inserted as strings.
Info on the plugin can be found here: http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/SingleTableInheritance.html.
> Configure Magma::Attribute sti key_map

- lib/magma/attribute.rb
- spec/magma_attribute_spec.rb
This validation will stop attributes from being inserted into the database via Sequel if `type` is not a supported type.
Fixes #192
> Validate Magma::Attribute#type is a supported type

- db/migrations/006_add_column_name_to_attributes.rb
- lib/magma/actions/add_attribute.rb
- lib/magma/actions/add_model.rb
- lib/magma/actions/base_action.rb
- lib/magma/actions/model_update_actions.rb
- lib/magma/actions/rename_attribute.rb
- lib/magma/attribute.rb
- lib/magma/project.rb
- spec/actions/add_attribute_actions_spec.rb
- spec/actions/add_model_action_spec.rb
- spec/actions/rename_attribute_action_spec.rb
This PR builds off of https://github.com/mountetna/magma/pull/199. `Magma::RenameAttributeAction` will change the given attribute's `attribute_name` without changing its `column_name`.
To facilitate this change, `Magma::Attribute`'s primary key (via `Sequel::Model`) was updated so it uses  `column_name` instead of `attribute_name`.
https://github.com/mountetna/magma/blob/333cf5a0b680949272b3f042a83e4436d18b45c2/lib/magma/attribute.rb#L1-L7
`column_name` will never change so it should be treated as part of the attribute's primary key.
This PR also changes the rollback behavior in `Magma::ModelUpdateActions`. Instead of rollback actions in the order they came in, it'll roll them back in reverse so we reset things back to their original state. …
> Add rename_attribute action
